#!/bin/bash

{
SCRIPT_DIR=$(dirname $(realpath "$0"))

function keep_idle {
	SLEEPTIME=60

	if ! command -v xdotool 2>/dev/null >/dev/null; then
		echo "xdotool not found. Cannot use keep_idle."
		return
	fi

	if ! command -v xprintidle 2>/dev/null >/dev/null; then
		echo "xprintidle not found. Cannot use keep_idle."
		return
	fi

	while true; do
		eval $(xdotool getmouselocation --shell)

		IDLETIME=$(xprintidle)
		IDLETIME=$(($IDLETIME/1000))
		if [[ $IDLETIME -gt $SLEEPTIME ]]; then
			xdotool mousemove $X $((Y-1))
		fi

		sleep $SLEEPTIME
	done
}

if ! command -v vlc 2>/dev/null >/dev/null; then
	echo "vlc not found. Cannot use watch2."
	return
fi

if ! command -v python3 2>/dev/null >/dev/null; then
	echo "python3 not found. Cannot use watch2."
	return
fi

if [[ ! -e $SCRIPT_DIR/.shellscript_functions ]]; then
	echo "$SCRIPT_DIR/.shellscript_functions was not found"
	exit 1
fi

if [[ ! -e $SCRIPT_DIR/.watch2.py ]]; then
	echo "$SCRIPT_DIR/.watch2.py was not found"
	exit 1
fi

source $SCRIPT_DIR/.shellscript_functions

keep_idle &
python3 $SCRIPT_DIR/.watch2.py $*

kill %1
}
